// Code generated by ent, DO NOT EDIT.

package ent

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyName(value string) *UserUpdate {
	if value != "" {
		return u.SetName(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyName(value string) *UserUpdateOne {
	if value != "" {
		return u.SetName(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyAvatar(value string) *UserUpdate {
	if value != "" {
		return u.SetAvatar(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyAvatar(value string) *UserUpdateOne {
	if value != "" {
		return u.SetAvatar(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyUsername(value string) *UserUpdate {
	if value != "" {
		return u.SetUsername(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyUsername(value string) *UserUpdateOne {
	if value != "" {
		return u.SetUsername(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyMobile(value string) *UserUpdate {
	if value != "" {
		return u.SetMobile(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyMobile(value string) *UserUpdateOne {
	if value != "" {
		return u.SetMobile(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyIDCard(value string) *UserUpdate {
	if value != "" {
		return u.SetIDCard(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyIDCard(value string) *UserUpdateOne {
	if value != "" {
		return u.SetIDCard(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdate) SetNotEmptyOpenpid(value string) *UserUpdate {
	if value != "" {
		return u.SetOpenpid(value)
	}
	return u
}

// set field if value is not empty. e.g. string does not equal to ""
func (u *UserUpdateOne) SetNotEmptyOpenpid(value string) *UserUpdateOne {
	if value != "" {
		return u.SetOpenpid(value)
	}
	return u
}
